name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build release
        run: cargo build --release
      - name: Run tests
        run: cargo test --release --verbose
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: hypr-tui-executable
          path: target/release/hypr-tui
