name: Rust (Linux build)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build release for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Run tests
        run: cargo test --release --verbose --target x86_64-unknown-linux-gnu

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: hypr-tui-linux
          path: target/x86_64-unknown-linux-gnu/release/hypr-tui
